/// Danh sách đầy đủ toàn bộ các quốc gia trên thế giới kèm mã ISO 3166-1 alpha-2 và Cờ Quốc kỳ (Emoji)
class Country {
  final String code;
  final String name;

  const Country({required this.code, required this.name});

  /// Chuyển đổi mã quốc gia 2 ký tự thành biểu tượng Cờ Emoji chuẩn Unicode
  String get flag {
    if (code.length != 2) return '🏳️';
    final int firstChar = code.toUpperCase().codeUnitAt(0) - 0x41 + 0x1F1E6;
    final int secondChar = code.toUpperCase().codeUnitAt(1) - 0x41 + 0x1F1E6;
    return String.fromCharCode(firstChar) + String.fromCharCode(secondChar);
  }

  String get displayName => '$name $flag';
}

/// Chuyển đổi mã ISO sang Cờ Emoji
String getCountryFlag(String code) {
  if (code.length != 2) return '🏳️';
  final int firstChar = code.toUpperCase().codeUnitAt(0) - 0x41 + 0x1F1E6;
  final int secondChar = code.toUpperCase().codeUnitAt(1) - 0x41 + 0x1F1E6;
  return String.fromCharCode(firstChar) + String.fromCharCode(secondChar);
}

const List<Country> allCountries = [
  Country(code: 'af', name: 'Afghanistan'),
  Country(code: 'al', name: 'Albania'),
  Country(code: 'dz', name: 'Algeria'),
  Country(code: 'ad', name: 'Andorra'),
  Country(code: 'ao', name: 'Angola'),
  Country(code: 'ag', name: 'Antigua & Barbuda'),
  Country(code: 'ar', name: 'Argentina'),
  Country(code: 'am', name: 'Armenia'),
  Country(code: 'au', name: 'Australia'),
  Country(code: 'at', name: 'Austria'),
  Country(code: 'az', name: 'Azerbaijan'),
  Country(code: 'bs', name: 'Bahamas'),
  Country(code: 'bh', name: 'Bahrain'),
  Country(code: 'bd', name: 'Bangladesh'),
  Country(code: 'bb', name: 'Barbados'),
  Country(code: 'by', name: 'Belarus'),
  Country(code: 'be', name: 'Belgium'),
  Country(code: 'bz', name: 'Belize'),
  Country(code: 'bj', name: 'Benin'),
  Country(code: 'bt', name: 'Bhutan'),
  Country(code: 'bo', name: 'Bolivia'),
  Country(code: 'ba', name: 'Bosnia & Herzegovina'),
  Country(code: 'bw', name: 'Botswana'),
  Country(code: 'br', name: 'Brazil'),
  Country(code: 'bn', name: 'Brunei'),
  Country(code: 'bg', name: 'Bulgaria'),
  Country(code: 'bf', name: 'Burkina Faso'),
  Country(code: 'bi', name: 'Burundi'),
  Country(code: 'kh', name: 'Cambodia'),
  Country(code: 'cm', name: 'Cameroon'),
  Country(code: 'ca', name: 'Canada'),
  Country(code: 'cv', name: 'Cape Verde'),
  Country(code: 'cf', name: 'Central African Republic'),
  Country(code: 'td', name: 'Chad'),
  Country(code: 'cl', name: 'Chile'),
  Country(code: 'cn', name: 'China'),
  Country(code: 'co', name: 'Colombia'),
  Country(code: 'km', name: 'Comoros'),
  Country(code: 'cg', name: 'Congo'),
  Country(code: 'cr', name: 'Costa Rica'),
  Country(code: 'hr', name: 'Croatia'),
  Country(code: 'cu', name: 'Cuba'),
  Country(code: 'cy', name: 'Cyprus'),
  Country(code: 'cz', name: 'Czech Republic'),
  Country(code: 'dk', name: 'Denmark'),
  Country(code: 'dj', name: 'Djibouti'),
  Country(code: 'dm', name: 'Dominica'),
  Country(code: 'do', name: 'Dominican Republic'),
  Country(code: 'ec', name: 'Ecuador'),
  Country(code: 'eg', name: 'Egypt'),
  Country(code: 'sv', name: 'El Salvador'),
  Country(code: 'gq', name: 'Equatorial Guinea'),
  Country(code: 'er', name: 'Eritrea'),
  Country(code: 'ee', name: 'Estonia'),
  Country(code: 'sz', name: 'Eswatini'),
  Country(code: 'et', name: 'Ethiopia'),
  Country(code: 'fj', name: 'Fiji'),
  Country(code: 'fi', name: 'Finland'),
  Country(code: 'fr', name: 'France'),
  Country(code: 'ga', name: 'Gabon'),
  Country(code: 'gm', name: 'Gambia'),
  Country(code: 'ge', name: 'Georgia'),
  Country(code: 'de', name: 'Germany'),
  Country(code: 'gh', name: 'Ghana'),
  Country(code: 'gr', name: 'Greece'),
  Country(code: 'gd', name: 'Grenada'),
  Country(code: 'gt', name: 'Guatemala'),
  Country(code: 'gn', name: 'Guinea'),
  Country(code: 'gw', name: 'Guinea-Bissau'),
  Country(code: 'gy', name: 'Guyana'),
  Country(code: 'ht', name: 'Haiti'),
  Country(code: 'hn', name: 'Honduras'),
  Country(code: 'hu', name: 'Hungary'),
  Country(code: 'is', name: 'Iceland'),
  Country(code: 'in', name: 'India'),
  Country(code: 'id', name: 'Indonesia'),
  Country(code: 'ir', name: 'Iran'),
  Country(code: 'iq', name: 'Iraq'),
  Country(code: 'ie', name: 'Ireland'),
  Country(code: 'il', name: 'Israel'),
  Country(code: 'it', name: 'Italy'),
  Country(code: 'ci', name: 'Ivory Coast'),
  Country(code: 'jm', name: 'Jamaica'),
  Country(code: 'jp', name: 'Japan'),
  Country(code: 'jo', name: 'Jordan'),
  Country(code: 'kz', name: 'Kazakhstan'),
  Country(code: 'ke', name: 'Kenya'),
  Country(code: 'ki', name: 'Kiribati'),
  Country(code: 'kw', name: 'Kuwait'),
  Country(code: 'kg', name: 'Kyrgyzstan'),
  Country(code: 'la', name: 'Laos'),
  Country(code: 'lv', name: 'Latvia'),
  Country(code: 'lb', name: 'Lebanon'),
  Country(code: 'ls', name: 'Lesotho'),
  Country(code: 'lr', name: 'Liberia'),
  Country(code: 'ly', name: 'Libya'),
  Country(code: 'li', name: 'Liechtenstein'),
  Country(code: 'lt', name: 'Lithuania'),
  Country(code: 'lu', name: 'Luxembourg'),
  Country(code: 'mg', name: 'Madagascar'),
  Country(code: 'mw', name: 'Malawi'),
  Country(code: 'my', name: 'Malaysia'),
  Country(code: 'mv', name: 'Maldives'),
  Country(code: 'ml', name: 'Mali'),
  Country(code: 'mt', name: 'Malta'),
  Country(code: 'mh', name: 'Marshall Islands'),
  Country(code: 'mr', name: 'Mauritania'),
  Country(code: 'mu', name: 'Mauritius'),
  Country(code: 'mx', name: 'Mexico'),
  Country(code: 'fm', name: 'Micronesia'),
  Country(code: 'md', name: 'Moldova'),
  Country(code: 'mc', name: 'Monaco'),
  Country(code: 'mn', name: 'Mongolia'),
  Country(code: 'me', name: 'Montenegro'),
  Country(code: 'ma', name: 'Morocco'),
  Country(code: 'mz', name: 'Mozambique'),
  Country(code: 'mm', name: 'Myanmar'),
  Country(code: 'na', name: 'Namibia'),
  Country(code: 'nr', name: 'Nauru'),
  Country(code: 'np', name: 'Nepal'),
  Country(code: 'nl', name: 'Netherlands'),
  Country(code: 'nz', name: 'New Zealand'),
  Country(code: 'ni', name: 'Nicaragua'),
  Country(code: 'ne', name: 'Niger'),
  Country(code: 'ng', name: 'Nigeria'),
  Country(code: 'kp', name: 'North Korea'),
  Country(code: 'mk', name: 'North Macedonia'),
  Country(code: 'no', name: 'Norway'),
  Country(code: 'om', name: 'Oman'),
  Country(code: 'pk', name: 'Pakistan'),
  Country(code: 'pw', name: 'Palau'),
  Country(code: 'ps', name: 'Palestine'),
  Country(code: 'pa', name: 'Panama'),
  Country(code: 'pg', name: 'Papua New Guinea'),
  Country(code: 'py', name: 'Paraguay'),
  Country(code: 'pe', name: 'Peru'),
  Country(code: 'ph', name: 'Philippines'),
  Country(code: 'pl', name: 'Poland'),
  Country(code: 'pt', name: 'Portugal'),
  Country(code: 'qa', name: 'Qatar'),
  Country(code: 'ro', name: 'Romania'),
  Country(code: 'ru', name: 'Russia'),
  Country(code: 'rw', name: 'Rwanda'),
  Country(code: 'kn', name: 'Saint Kitts & Nevis'),
  Country(code: 'lc', name: 'Saint Lucia'),
  Country(code: 'vc', name: 'Saint Vincent'),
  Country(code: 'ws', name: 'Samoa'),
  Country(code: 'sm', name: 'San Marino'),
  Country(code: 'st', name: 'Sao Tome & Principe'),
  Country(code: 'sa', name: 'Saudi Arabia'),
  Country(code: 'sn', name: 'Senegal'),
  Country(code: 'rs', name: 'Serbia'),
  Country(code: 'sc', name: 'Seychelles'),
  Country(code: 'sl', name: 'Sierra Leone'),
  Country(code: 'sg', name: 'Singapore'),
  Country(code: 'sk', name: 'Slovakia'),
  Country(code: 'si', name: 'Slovenia'),
  Country(code: 'sb', name: 'Solomon Islands'),
  Country(code: 'so', name: 'Somalia'),
  Country(code: 'za', name: 'South Africa'),
  Country(code: 'kr', name: 'South Korea'),
  Country(code: 'ss', name: 'South Sudan'),
  Country(code: 'es', name: 'Spain'),
  Country(code: 'lk', name: 'Sri Lanka'),
  Country(code: 'sd', name: 'Sudan'),
  Country(code: 'sr', name: 'Suriname'),
  Country(code: 'se', name: 'Sweden'),
  Country(code: 'ch', name: 'Switzerland'),
  Country(code: 'sy', name: 'Syria'),
  Country(code: 'tw', name: 'Taiwan'),
  Country(code: 'tj', name: 'Tajikistan'),
  Country(code: 'tz', name: 'Tanzania'),
  Country(code: 'th', name: 'Thailand'),
  Country(code: 'tl', name: 'Timor-Leste'),
  Country(code: 'tg', name: 'Togo'),
  Country(code: 'to', name: 'Tonga'),
  Country(code: 'tt', name: 'Trinidad & Tobago'),
  Country(code: 'tn', name: 'Tunisia'),
  Country(code: 'tr', name: 'Turkey'),
  Country(code: 'tm', name: 'Turkmenistan'),
  Country(code: 'tv', name: 'Tuvalu'),
  Country(code: 'ug', name: 'Uganda'),
  Country(code: 'ua', name: 'Ukraine'),
  Country(code: 'ae', name: 'United Arab Emirates'),
  Country(code: 'gb', name: 'United Kingdom'),
  Country(code: 'us', name: 'United States'),
  Country(code: 'uy', name: 'Uruguay'),
  Country(code: 'uz', name: 'Uzbekistan'),
  Country(code: 'vu', name: 'Vanuatu'),
  Country(code: 'va', name: 'Vatican City'),
  Country(code: 've', name: 'Venezuela'),
  Country(code: 'vn', name: 'Vietnam'),
  Country(code: 'ye', name: 'Yemen'),
  Country(code: 'zm', name: 'Zambia'),
  Country(code: 'zw', name: 'Zimbabwe'),
];
